title: Portafolio 
description: Portafolio de Breitner Gonzalez Angarita
sitename: Breitner Gonzalez
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME